power <- read.csv("household_power_consumption.csv", sep=";", na.strings="?")
power <- subset(power, Date == "1/2/2007" | Date == "2/2/2007")
dt <- strptime(paste(power$Date, power$Time), format="%d/%m/%Y %H:%M:%S")
png(filename="plot3.png")
plot(x=dt, y=power[,"Sub_metering_1"], type="l",ylab="Energy sub metering", main="", xlab="")
lines(x=dt, y=power[,"Sub_metering_2"], col="red")
lines(x=dt, y=power[,"Sub_metering_3"], col="blue")
legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
